//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQSMessageReceiver.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Insert AWS public key here")]
        public string accessPKey {
            get {
                return ((string)(this["accessPKey"]));
            }
            set {
                this["accessPKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Insert AWS private key here")]
        public string accessSKey {
            get {
                return ((string)(this["accessSKey"]));
            }
            set {
                this["accessSKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Insert Amazon SQS URL here")]
        public string accessURL {
            get {
                return ((string)(this["accessURL"]));
            }
            set {
                this["accessURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter workbench directory here(Should be same as DEXGet and ISpy Reports workbenc" +
            "h directory)")]
        public string Database_Path {
            get {
                return ((string)(this["Database_Path"]));
            }
            set {
                this["Database_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DEX\\SQS Messages\\")]
        public string SQS_Messages_Folder {
            get {
                return ((string)(this["SQS_Messages_Folder"]));
            }
            set {
                this["SQS_Messages_Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Error Logs\\AmazonSQSMessageReceiver\\")]
        public string Session_Log_Folder {
            get {
                return ((string)(this["Session_Log_Folder"]));
            }
            set {
                this["Session_Log_Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Excel Files\\Input\\input.xml")]
        public string Excel_File {
            get {
                return ((string)(this["Excel_File"]));
            }
            set {
                this["Excel_File"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DEX\\Machine Database\\")]
        public string Machine_DB {
            get {
                return ((string)(this["Machine_DB"]));
            }
            set {
                this["Machine_DB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Luci Files\\DEX File Tray\\")]
        public string Dex_Tray {
            get {
                return ((string)(this["Dex_Tray"]));
            }
            set {
                this["Dex_Tray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DEX\\Archive\\")]
        public string Dex_Archive {
            get {
                return ((string)(this["Dex_Archive"]));
            }
            set {
                this["Dex_Archive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DEX\\Machine Archive\\")]
        public string Machine_Archive {
            get {
                return ((string)(this["Machine_Archive"]));
            }
            set {
                this["Machine_Archive"] = value;
            }
        }
    }
}
